apiVersion: v1
kind: Service
metadata:
  name: client
  annotations:
    liqo.io/skip-reflection: "true"
spec:
  ports:
    - name: client
      port: 9094
      targetPort: client
      protocol: TCP
  selector:
    flwr.liqo.io: client
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: client
spec:
  replicas: 3
  serviceName: client
  # podManagementPolicy: Parallel
  selector:
    matchLabels:
      flwr.liqo.io: client
  template:
    metadata:
      labels:
        flwr.liqo.io: client
    spec:
      initContainers:
        - name: supernode
          image: flwr/supernode:1.11.0
          args:
            - --insecure
            - --superlink
            - server:9092
            - --supernode-address
            - 127.0.0.1:9094
            - --isolation
            - process
            - --node-config
            - "partition-id=$(ID_CLIENT) num-partitions=$(NUM_CLIENTS)"
          ports:
            - containerPort: 9094
              name: supernode
              protocol: TCP
          restartPolicy: Always   # sidecar container (k8s >= 1.29) 
          env:
          - name: ID_CLIENT
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['apps.kubernetes.io/pod-index'] # require PodIndexLabel feature gate (k8s >= 1.28)
          - name: NUM_CLIENTS
            value: "3" # must match the number of replicas
      containers:
        - name: clientapp
          image: ghcr.io/arubakube/flwr/clientapp:0.0.1-cpu
          args:
            - --supernode
            - 127.0.0.1:9094
          resources:
            limits:
              cpu: 3
              memory: 2Gi
      restartPolicy: Always
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: flwr.liqo.io
                    operator: In
                    values:
                      - client
              topologyKey: kubernetes.io/hostname
      runtimeClassName: liqo
